// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "soberkoder@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/aeroports": {
            "get": {
                "description": "retourne au format JSON tous les aeroports",
                "summary": "récupérer tous les aeroports",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/mesure/{aeroport}/{date}": {
            "get": {
                "description": "get basic",
                "summary": "retourne la moyenne des mesures sur une journée d'un aeroport",
                "parameters": [
                    {
                        "type": "string",
                        "description": "aeroport Name",
                        "name": "aeroport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date AAAA-MM-JJ",
                        "name": "date",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Aeroport API",
	Description:      "Cette API vous permet d'effectuer deux get",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
