basePath: /
definitions:
  main.DayMeasurement:
    properties:
      HeureMesure:
        items:
          $ref: '#/definitions/main.HourMeasurement'
        type: array
      jour:
        type: string
    type: object
  main.HourMeasurement:
    properties:
      Mesure:
        $ref: '#/definitions/main.Measurement'
      heure:
        type: string
    type: object
  main.Measurement:
    properties:
      Value:
        type: number
      idCapteur:
        type: string
    type: object
  main.MeasuresResultat:
    properties:
      pressions:
        items:
          $ref: '#/definitions/main.DayMeasurement'
        type: array
      temperatures:
        items:
          $ref: '#/definitions/main.DayMeasurement'
        type: array
      vitesseVents:
        items:
          $ref: '#/definitions/main.DayMeasurement'
        type: array
    type: object
host: localhost:8080
info:
  contact:
    email: soberkoder@swagger.io
    name: API Support
  description: Cette API vous permet d'effectuer deux get
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Aeroport API
  version: "1.0"
paths:
  /api/aeroports:
    get:
      description: retourne au format JSON tous les aeroports
      responses:
        "200":
          description: OK
      summary: récupérer tous les aeroports
  /api/allMesure/{iata}/{annee}/{mois}/{jour}:
    get:
      description: get basic
      parameters:
      - description: aeroport Name
        in: path
        name: iata
        required: true
        type: string
      - description: Date AAAA
        in: path
        name: annee
        required: true
        type: string
      - description: Date MM
        in: path
        name: mois
        required: true
        type: string
      - description: Date JJ
        in: path
        name: jour
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: retourne la moyenne des mesures sur une journée d'un aeroport
  /api/mesures/{iata}/{start}/{end}:
    get:
      parameters:
      - description: aeroport Name
        in: path
        name: iata
        required: true
        type: string
      - description: 'Start (format: YYYY-MM-DD-HH)'
        in: path
        name: start
        required: true
        type: string
      - description: 'End (format: YYYY-MM-DD-HH)'
        in: path
        name: end
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.MeasuresResultat'
            type: array
swagger: "2.0"
